package edu.ucla.util.code;

import java.io.*;

/** @author Keith Cascio
	@since 032405 */
public class JDKCompile extends JDKToolScript implements Script
{
	public String getName(){
		return "compile";
	}

	public String getDescriptionComment(){
		return "This script compiles Java code generated by Code Bandit";
	}

	public String getUsage(){
		return "<*.java files>";
	}

	public String getUsageExample(){
		return "FooTutorial.java";
	}

	public String getDefaultFileName(){
		return "cbcompile";
	}

	protected String getMessageSuccess( String argsFlat ){
		return "Finished compiling " + argsFlat;
	}

	protected String getDescription( String argsFlat ){
		return "Compilation of " + argsFlat;
	}

	public String[] getCommandArray( ScriptGenius genius, SystemSoftwareSource source ) throws Exception{
		File javacpath = source.getExecutablePath( JDKTool.getJavacTool() );
		if( javacpath == null ) throw new Exception( JDKTool.getJavacTool().getDescriptionShort() + " not found" );

		File classpathinflib = source.getClasspath( ClassModule.getInflibModule() );
		if( classpathinflib == null ) throw new Exception( ClassModule.getInflibModule().getDescriptionShort() + " not found" );

		String[] cmdarray = new String[]{
			javacpath.getAbsolutePath(),
			"-classpath",
			classpathinflib.getAbsolutePath()
		};

		return cmdarray;
	}

	protected SoftwareEntity[] makeDependencies(){
		return new SoftwareEntity[] { ClassModule.getInflibModule(), JDKTool.getJavacTool() };
	}
}
