/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_ucla_belief_io_dsl_SMILEReader */

#ifndef _Included_edu_ucla_belief_io_dsl_SMILEReader
#define _Included_edu_ucla_belief_io_dsl_SMILEReader
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: FLAG_VERBOSE */
#undef edu_ucla_belief_io_dsl_SMILEReader_ARGUMENT_LIST_SIZE_SANS_TARGETS_LIST
#define edu_ucla_belief_io_dsl_SMILEReader_ARGUMENT_LIST_SIZE_SANS_TARGETS_LIST 11L
#undef edu_ucla_belief_io_dsl_SMILEReader_INDEX_X_POSITION
#define edu_ucla_belief_io_dsl_SMILEReader_INDEX_X_POSITION 0L
#undef edu_ucla_belief_io_dsl_SMILEReader_INDEX_Y_POSITION
#define edu_ucla_belief_io_dsl_SMILEReader_INDEX_Y_POSITION 1L
#undef edu_ucla_belief_io_dsl_SMILEReader_INDEX_WIDTH
#define edu_ucla_belief_io_dsl_SMILEReader_INDEX_WIDTH 2L
#undef edu_ucla_belief_io_dsl_SMILEReader_INDEX_HEIGHT
#define edu_ucla_belief_io_dsl_SMILEReader_INDEX_HEIGHT 3L
#undef edu_ucla_belief_io_dsl_SMILEReader_INDEX_DSLNodeType
#define edu_ucla_belief_io_dsl_SMILEReader_INDEX_DSLNodeType 4L
#undef edu_ucla_belief_io_dsl_SMILEReader_INDEX_DiagnosisType
#define edu_ucla_belief_io_dsl_SMILEReader_INDEX_DiagnosisType 5L
#undef edu_ucla_belief_io_dsl_SMILEReader_INDEX_MANDATORY
#define edu_ucla_belief_io_dsl_SMILEReader_INDEX_MANDATORY 6L
#undef edu_ucla_belief_io_dsl_SMILEReader_INDEX_RANKED
#define edu_ucla_belief_io_dsl_SMILEReader_INDEX_RANKED 7L
#undef edu_ucla_belief_io_dsl_SMILEReader_INDEX_DEFAULT_STATE_INDEX
#define edu_ucla_belief_io_dsl_SMILEReader_INDEX_DEFAULT_STATE_INDEX 8L
#undef edu_ucla_belief_io_dsl_SMILEReader_INDEX_SUBMODEL_HANDLE
#define edu_ucla_belief_io_dsl_SMILEReader_INDEX_SUBMODEL_HANDLE 9L
#undef edu_ucla_belief_io_dsl_SMILEReader_INDEX_NUM_TARGETS
#define edu_ucla_belief_io_dsl_SMILEReader_INDEX_NUM_TARGETS 10L
#undef edu_ucla_belief_io_dsl_SMILEReader_INDEX_BEGIN_TARGETS_LIST
#define edu_ucla_belief_io_dsl_SMILEReader_INDEX_BEGIN_TARGETS_LIST 11L
#undef edu_ucla_belief_io_dsl_SMILEReader_ARGUMENT_LIST_SIZE_UPDATE
#define edu_ucla_belief_io_dsl_SMILEReader_ARGUMENT_LIST_SIZE_UPDATE 1L
#undef edu_ucla_belief_io_dsl_SMILEReader_INDEX_UPDATE_DiagnosisType
#define edu_ucla_belief_io_dsl_SMILEReader_INDEX_UPDATE_DiagnosisType 0L
#undef edu_ucla_belief_io_dsl_SMILEReader_DSL_CPT
#define edu_ucla_belief_io_dsl_SMILEReader_DSL_CPT 0L
#undef edu_ucla_belief_io_dsl_SMILEReader_DSL_NOISY_MAX
#define edu_ucla_belief_io_dsl_SMILEReader_DSL_NOISY_MAX 1L
#undef edu_ucla_belief_io_dsl_SMILEReader_DSL_TRUTHTABLE
#define edu_ucla_belief_io_dsl_SMILEReader_DSL_TRUTHTABLE 2L
#undef edu_ucla_belief_io_dsl_SMILEReader_UNDEFINED_NODE_TYPE
#define edu_ucla_belief_io_dsl_SMILEReader_UNDEFINED_NODE_TYPE -1L
#undef edu_ucla_belief_io_dsl_SMILEReader_TARGET
#define edu_ucla_belief_io_dsl_SMILEReader_TARGET 0L
#undef edu_ucla_belief_io_dsl_SMILEReader_OBSERVATION
#define edu_ucla_belief_io_dsl_SMILEReader_OBSERVATION 1L
#undef edu_ucla_belief_io_dsl_SMILEReader_AUXILIARY
#define edu_ucla_belief_io_dsl_SMILEReader_AUXILIARY 2L
/* Inaccessible static: one */
/* Inaccessible static: zero */
/* Inaccessible static: FLAG_LOADLIBRARY_FAILED */
/*
 * Class:     edu_ucla_belief_io_dsl_SMILEReader
 * Method:    loadDSL
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_edu_ucla_belief_io_dsl_SMILEReader_loadDSL
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     edu_ucla_belief_io_dsl_SMILEReader
 * Method:    updateDSL
 * Signature: (Ljava/lang/String;ILjava/lang/String;I[Ljava/lang/String;[[D[Ljava/lang/String;[Ljava/lang/String;[[Ljava/lang/String;[[Ljava/lang/String;[[I)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_ucla_belief_io_dsl_SMILEReader_updateDSL
  (JNIEnv *, jobject, jstring, jint, jstring, jint, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jobjectArray);

/*
 * Class:     edu_ucla_belief_io_dsl_SMILEReader
 * Method:    librarySupports
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_ucla_belief_io_dsl_SMILEReader_librarySupports
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
