/* Generated By:JavaCC: Do not edit this line. HuginLogReaderConstants.java */
package edu.ucla.belief.io.hugin;

public interface HuginLogReaderConstants {

  int EOF = 0;
  int COMMENT = 5;
  int MORAL_LIT1 = 6;
  int MORAL_LIT2 = 7;
  int AND_LIT = 8;
  int TRIAGULATE_LIT1 = 9;
  int TRIAGULATE_LIT2 = 10;
  int TRIAGULATE_LIT3 = 11;
  int TRIANGULATE_LIT5 = 12;
  int TRIANGULATE_LIT6 = 13;
  int TRIANGULATE_LIT7 = 14;
  int TRIANGULATE_LIT8 = 15;
  int TRIAGULATE_LIT4 = 16;
  int ELIMINATION_LIT = 17;
  int CLIQUES_LIT1 = 18;
  int CLIQUE_DECL_LIT1 = 19;
  int CLIQUE_DECL_LIT2 = 20;
  int CLIQUE_DECL_LIT3 = 21;
  int CLIQUES_LIT2 = 22;
  int JUNCTION_FOREST_LIT = 23;
  int JUNCTION_TREE_DECL_LIT1 = 24;
  int JUNCTION_TREE_DECL_LIT2 = 25;
  int LINK_DECL_LIT1 = 26;
  int LINK_DECL_LIT2 = 27;
  int LINK_DECL_LIT3 = 28;
  int ASSIGNMENTS_LIT = 29;
  int ASSIGNMENTS_DECL_LIT1 = 30;
  int ASSIGNMENTS_DECL_LIT2 = 31;
  int ID = 32;
  int NUM = 33;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<COMMENT>",
    "\"Moral links:\"",
    "\"Marrying\"",
    "\"and\"",
    "\"Triangulating prime component with\"",
    "\"members:\"",
    "\"This component is a clique of cost\"",
    "\"Using minimum fill-in weight heuristic for triangulation:\"",
    "\"Eliminating\"",
    "\"Creating fill-in between\"",
    "\"Found triangulation of prime component of cost\"",
    "\"Total cost of triangulation for all prime components is\"",
    "\"Elimination sequence:\"",
    "\"Cliques:\"",
    "\"Clique\"",
    "\"members (\"",
    "\"), table size =\"",
    "\"Total clique table size:\"",
    "\"The junction forest:\"",
    "\"Creating junction tree with clique\"",
    "\"as root ...\"",
    "\"Cliques\"",
    "\"linked, separated by {\"",
    "\"} (table size =\"",
    "\"Assignment of potentials to cliques:\"",
    "\"Node\"",
    "\"assigned to clique\"",
    "<ID>",
    "<NUM>",
    "\":\"",
    "\",\"",
    "\")\"",
  };

}
