/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_ucla_belief_dtree_Hmetis */

#ifndef _Included_edu_ucla_belief_dtree_Hmetis
#define _Included_edu_ucla_belief_dtree_Hmetis
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: loaded */
/*
 * Class:     edu_ucla_belief_dtree_Hmetis
 * Method:    HMETIS_PartRecursive
 * Signature: (II[I[I[I[III[I[I[I[D)I
 */
JNIEXPORT jint JNICALL Java_edu_ucla_belief_dtree_Hmetis_HMETIS_1PartRecursive
  (JNIEnv *, jclass, jint, jint, jintArray, jintArray, jintArray, jintArray, jint, jint, jintArray, jintArray, jintArray, jdoubleArray);

/*
 * Class:     edu_ucla_belief_dtree_Hmetis
 * Method:    HMETIS_PartKway
 * Signature: (II[I[I[I[III[I[I[I[D)I
 */
JNIEXPORT jint JNICALL Java_edu_ucla_belief_dtree_Hmetis_HMETIS_1PartKway
  (JNIEnv *, jclass, jint, jint, jintArray, jintArray, jintArray, jintArray, jint, jint, jintArray, jintArray, jintArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
