#!/bin/sh
# Script to write dtree
# by Keith Cascio

# usage: write_dtree -i<input path> [-o<output path>] [-m<memory limit in MB>]

# example: write_dtree -ic:\networks\barley.net -oc:\dtrees\barley_dtree.dat -m20.1

# NOTE: This program allows no white space between each command line flag and its argument.
# e.g.   correct usage: "write_dtree -i/networks/cancer.net"
# e.g. incorrect usage: "write_dtree -i /networks/cancer.net"

# NOTE: The argument to -m must be a non-negative floating point number.  e.g. -m20, -m0.001, -m1024.5

# Explanation of command-line flags:
#
# -Xms8m: Specify the initial size, in bytes, of the java virtual machine memory allocation pool = 8 Megs.
#
# -Xmx512m: Specify the maximum size, in bytes, of the java virtual machine memory allocation pool = 512 Megs.

java -Xms8m -Xmx512m -classpath inflib.jar edu.ucla.belief.inference.RCInfo $*
