#!/bin/bash

[ -x '/usr/local/bin/gnugrep'  ] && GREP='/usr/local/bin/gnugrep';
[ -z "$GREP" -a -x '/bin/grep' ] && GREP='/bin/grep';

export LC_ALL=C;
export LC_COLLATE=C;

find edu -name CVS -prune -o -name "*.java" -print | $GREP -Ev 'FishEye|OpacityConsultant|actionsandmodes/Grep|CrouchingTiger|OutputPanel5|EnumPropertyEditPanel5|EnumTableModel5|DisplayableBeliefNetwork5|NetworkGrep|LingoPreference|EnumPreference|Dropdown' | sort > files.txt
